name: Logtime Automation

on:
  schedule:
    - cron: "0 7 * * *"  # Tous les jours à 7h UTC (8h Paris)
  workflow_dispatch:

jobs:
  send-logtime:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: pip3 install requests python-dotenv

      - name: Run script
        run: python3 script.py
