name: Logtime Automation

on:
  schedule:
    - cron: '30 11 * * *'  # Exécution tous les jours à 19h30 heure française
    - cron: '05 18 * * *'  # Exécution tous les jours à 19h05 UTC
    - cron: '00 08 * * *'
  workflow_dispatch:  # Permet de le lancer manuellement

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip3 install requests python-dotenv

      - name: Run script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python3 script.py
